# Install

This chapter describes the process for installing and configuring the FluvialGeomorph toolbox and its required software components. 


## Software Requirements
Here is a summary of the software that must be installed to use the FluvialGeomorph toolbox. The rest of this chapter will describe how to complete these installations. 

* Windows OS (10+ recommended, Server 2019). ArcGIS desktop GIS applications are only provided by ESRI for the Windows platform.
* R Statistical Computing Language (3.6.3+ recommended)
* RStudio Desktop (1.3+ recommended)
* TauDEM (5.3.7+ recommended)
* ArcGIS Pro (2.6+ recommended) 
* ArcGIS Desktop (10.8+ recommended), optional, limited support
* FluvialGeomorph toolbox, latest version


## Install `R`
[`R`](https://cran.r-project.org/) is a statistical computing environment required to perform calculations and report generation (@R-base). 

* Ensure that `R` is installed. 
* `R` version 3.6.3 or greater is recommended. 
* Ensure that `RTools` is installed. You will need either  [`RTools35`](https://cran.r-project.org/bin/windows/Rtools/history.html) for `R` v3.6.x or [`RTools40`](https://cran.r-project.org/bin/windows/Rtools/) for `R` v4.x. `RTools` is required for compiling `R` packages from source. It is highly recommended, but not strictly required. 
* Ensure that your `RTools` installation is on the system `PATH` (i.e., open a command prompt window, use the `path` command). If not, set your user environment `PATH` variable to the appropriate (depending on the `R` major version) `RTools` `bin` directory (e.g., `C:\Rtools\bin`, `C:\rtools40\usr\bin`). 

## Install `RStudio`
`Rstudio` is an Integrated Development Environment (IDE) for `R` that streamlines development and troubleshooting. 

* Ensure that `Rstudio` is installed.
* `RStudio` version 1.3 or greater is recommended. 
* `RStudio` is recommended, but not strictly required. 
* Update your currently installed `R` packages to the latest version. On the `RStudio` tools menu, select "Check for Package Updates...". Click the "Select All" button and click the "Install Updates" button. 
* If asked to compile packages from source, select "Yes" if you installed `RTools`. 


## Install TauDEM
[`TauDEM`](https://hydrology.usu.edu/taudem/taudem5/index.html) (**T**errain **A**nalysis **U**sing **D**igital **E**levation **M**odels) is a suite of Digital Elevation Model (DEM) tools for the extraction and analysis of hydrologic information from topography as represented by a DEM (@tarboton_new_1997, @fan_accelerating_2014, @yldrm_accelerating_2016). `TauDEM` is used for advanced DEM processing and synthetic stream delineation. 

* Install the latest version of [`TauDEM`](https://hydrology.usu.edu/taudem/taudem5/downloads.html), v5.3.7.
* Ensure that `TauDEM` is on the system `PATH`. If not, set your user environment `PATH` variable to the `TauDEM` executable directory (e.g., `C:\Program Files\TauDEM\TauDEM5Exe`). 


## Install `ArcGIS Pro`
ESRI `ArcGIS Pro` is the GIS application where the FluvialGeomorph analysis will be performed and where the toolbox will be accessed.   

* Ensure that `ArcGIS Pro` is installed. 
* `ArcGIS Pro` version 2.6+ is recommended. 


### Limited `ArcMap` Support
ESRI `ArcMap` can currently be used to run the FluvialGeomorph toolbox, but use of `ArcGIS Pro` provides more functionality (e.g., charting, map templates, etc.). As the `ArcMap` application approaches end of life, it will no longer be supported by the FluvialGeomorph toolbox. As `ArcMap` is a 32-bit application, some `R` functions currently do not always perform as expected under 32-bit `R`. If you expect to get the most out of the FluvialGeomorph toolbox, migrate now to `ArcGIS Pro` to take advantage of the latest data formats, geoprocessing speed, Python 3, and 64-bit `R`.  


### Download the `arcgisbinding` package
The `arcgisbinding` `R` package allows `ArcGIS Pro` and `ArcMap` to read and write to `R` sessions. Installing it through `ArcGIS Pro` also enables it for use in `ArcMap` as well. See the [NEWS](NEWS.md) for more details on version compatibility. Please manually download the specified version using these instructions:

* Navigate to the following URL: [https://github.com/R-ArcGIS/r-bridge](https://github.com/R-ArcGIS/r-bridge)
* In the "Releases" section on the middle-right side of the page, click the "+ xx releases" link. 
* Download the `v1.0.1.239` version. This file is named: `arcgisbinding_1.0.1.239.zip`
* Note the location of the file you just downloaded. We will use it in a following step.


### Install the `arcgisbinding` package
The `arcgisbinding` `R` package is developed and maintained by ESRI to support the import and export of GIS data into `R`. 

* In `ArcGIS Pro`, on the top menu, click "Project", and click "Options" on the left menu.
* In the "Options" dialog box, click "Geoprocessing" on the left menu. 
* On the "Geoprocessing" page, scroll down to the "R-ArcGIS Support" section.
* In the "R-ArcGIS Support" section, verify the installed `R` version for ArcGIS to use.
* Select an `R` version in the 3.6.x series.  
* Below the "Detected R home directories" drop-down menu, you will see the `arcgisbinding` package section. From the drop-down, choose the "Update from file" option. Navigate to the `arcgisbinding_1.0.1.239.zip` file you downloaded in an earlier step and click the OK button. 


## Install FluvialGeomorph
The code in the [FluvialGeomorph-toolbox/](https://github.com/FluvialGeomorph/FluvialGeomorph-toolbox/) repository contains all of the files needed to use this ArcGIS toolbox. 

* Open a web browser and navigate to [https://github.com/FluvialGeomorph/FluvialGeomorph-toolbox/](https://github.com/FluvialGeomorph/FluvialGeomorph-toolbox/). 
* In the "Releases" section in the upper right side of the page, click the green "latest" link. 
* On the latest release page, use the "Source code (zip)" link toward the bottom of the page to download a ZIP archive of the toolbox. 
* Copy the ZIP archive file to your project working directory. 
* If you already have a previous version of the FluvialGeomorph toolbox, delete it now. 
* Unzip the archive file of the latest version to your project folder. 
* In `ArcMap` or `ArcGIS Pro`, navigate to the folder where you just unzipped the archive and you are ready to use this ArcGIS toolbox. 

### Test the Toolbox
In this section we will test your FluvialGeomorph toolbox installation. 


### Troubleshooting


## Install Tutorial Data




