# Create Terrain
The purpose of this stage is to develop the terrain models for the project study area for all available LiDAR surveys. 

## Define Study Area
The purpose of this step is to define the location and extent of the study area. FluvialGeomorph project study areas are typically of three types, distinguished by their extent:

* **Small Reach** - Required by projects analyzing a problem at a specific location. These project study areas are typically defined by a single point location, often representing a piece of built infrastructure (e.g., bridge, culvert, stream crossing, dam, revetment, gage, etc.) or specific stream feature (e.g., stream confluence, bank failure, severe bed erosion, oxbow cutoff, etc.). Analysis of these problems usually only requires examining a fixed distance up and down stream of the feature of interest. This distance up and down stream is determined by the scale of the driving factors.  
* **Long Reach** - Required by projects analyzing a problem that spans a long set of connected stream reaches. These projects study areas are typically defined by several miles of stream, possibly including tributaries to the primary reach being analyzed. 
* **Watershed** - Required by projects analyzing watershed scale problems. FluvialGeomporh analysis of all streams in watersheds ranging in size from 1-3 HUC12 watersheds is feasible. 

### Create Study Area Geodatabases
The purpose of this step is to create a folder structure to store the the study area elevation data. Sub-folders will be created to store the terrain data for each available [LiDAR survey](#units_of_analysis). Initially, you will not know what LiDAR surveys exist for your study area until you begin your search for data described below. You will repeat the following steps for each LiDAR survey that exists for this project study area. The elevation data for each LiDAR survey will be processed separately and a synthetic stream network will be derived for each LiDAR survey independently. You will begin processing the data for the [base year](#units_of_analysis) LiDAR survey first, then work backward in time to process earlier LiDAR surveys in reverse chronological order. Several analysis steps require the base year data to be processed first. For some tools, surveys prior to the base year use the base year data as inputs. This is done to express earlier surveys in terms of the base year for comparison purposes. 

Use the following steps to organize the project working directory:   

* Create a new folder on a local workstation drive. Name it for the project study area. 
* Within the project study area folder create an `Elevation` folder. 
* Within the `Elevation` folder, create folders to store the data for each LiDAR survey. 
* Name each folder using the project name and suffixed with the LiDAR survey year (<project name>_<LiDAR survey 4-digit year>). 
* Within each LiDAR survey folder, create a new folder named `LAS`. This will be used in later steps if needed to store and process the raw LiDAR data for each survey. 
* Within each LiDAR survey folder, create a new LiDAR survey file geodatabase. 
* Name each file geodatabase using the project name and suffixed with the LiDAR survey year (<project name>_<LiDAR survey 4-digit year>). 
* Use the following folder structure to organize the terrain data: 

```
Project_Name
└─── Elevation
│    └─── ProjectName_Year1
│    │    └─── LAS
│    │    ProjectName_Year1.gdb
│    └─── ProjectName_Year2
│    |    └─── LAS
│    |    ProjectName_Year2.gdb
│    └─── ProjectName_Year3
│         └─── LAS
│         ProjectName_Year3.gdb
│         ...
└─── Exports
└─── Maps
```

### Define Study Area Coordinate System
The purpose of this step is to choose a horizontal and vertical coordinate system for all of the vector and raster datasets created in this project. Using the same coordinate system for all project datasets helps avoid errors introduced by input datasets containing differing coordinate systems, particularly incorrect handling of datums and units. The horizontal and vertical coordinate systems that you select will be used for all datasets created for this project. It is the analyst's responsibility to ensure that each dataset in this project uses these specified horizontal and vertical coordinate systems. Each dataset imported into a project geodatabase must be projected into the project horizontal and vertical coordinate systems. 

* **Horizontal Coordinate Systems** - FluvialGeomorph currently supports any *projected* coordinate system with linear units of meter, feet, or US survey feet. Geographic coordinate systems (angular units, e.g., "Lat-Lon") are not supported.   
* **Vertical Coordinate Systems** - FluvialGeomporh currently *only supports vertical coordinate systems with units of feet*. Since most LiDAR is currently delivered in the NAVD 88 vertical datum, it is recommended to use NAVD 88 for consistency. The analyst must be sure that the raster DEMs created for analysis in this chapter have vertical units of feet. Instructions for converting raster DEM values from meters to feet are included below. 


### Define Study Area Longitudinal Extent
The purpose of this step is to help define an initial study area longitudinal extent. This step will use existing, medium resolution hydrography to help establish the rough extent of the study area. The feature classes imported in this step will be used only as an initial coarse-scale representation of the study reaches to facilitate early study area definition. This study will derive high resolution definitions of study reaches. 

* Open the [National Map Viewer](https://apps.nationalmap.gov/viewer/) in a web browser. 
* In the National Map Viewer, zoom to the extent of the project study area. 
* From the toolbar, open the `Layer List` panel. 
* On the `Layer List` panel, toggle-on the visibility of the `National Hydrography Dataset` (NHD). 
* Under the `National Hydrography Dataset`, toggle-off the visibility of all other NHD datasets except the `Flowline - Large Scale` layer. Note, you must zoom in to a fine enough scale for this layer to be visible. 
* From the toolbar, open the `Select` panel. To begin, make all layers unselectable. 
* Scroll down to the `Flowline - Large Scale` layer and check the box to select features from this layer. 
* In the map panel, draw a rectangle around the extent of the NHD Flowline that represents your project area. 
* On the `Select` panel, click the "three dot" menu of the `Flowline - Large Scale` layer. Select the `Export to GeoJSON` option and save the export file in the `ProjectName_Year1` folder. 
* Open ArcGIS Pro and create a new project, saving it to the `\Project_Name\Maps` folder. 
* In ArcGIS Pro, use the `JSON to Features` tool to convert the exported NHD Flowline JSON features into the `ProjectName_Year1.gdb` file geodatabase. 
* Use the Data Management `Project` tool to project (verb) the imported NHD Flowline features to the chosen project (noun) coordinate system. Name the re-projected feature class `NHD_Flowline`. 
* Edit the extent of the `NHD_Flowline` feature class to match the desired extent of the project study area. 

### Define Study Area Areal Extent
The purpose of this step is to create a rough bounding polygon of the project study area. This polygon should define the "must-have" extent for both communicating the extent of the study area, as well as helping to define the area within which to acquire elevation data. This extent only needs to cover the extent of the stream to be analyzed and *does not* need to include the entire contributing area of the analysis reaches.  

* In ArcGIS Pro, in the `ProjectName_Year1.gdb` file geodatabase, create a new feature class using the following parameters:
  * Name: [`study_area`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#study-area-fc)
  * Feature Class Type: polygon
  * Field: `Project`, text 50
  * Horizontal Coordinate System: project horizontal coordinate system
  * Vertical Coordinate System: project vertical coordinate system
* Edit the extent of this polygon to outline the extent of the study area. 
* Ensure that full extent of the project study area floodplain is included within the extent of the `study_area` polygon feature class. 
* Set the value of the `study_area` `Project` field to the name of the study area. 

### Determine Study Area Contributing Watershed
The purpose of this step is to define the rough contributing area of the project study area. The  contributing area polygon derived in this step is almost always larger than the `study_area` polygon, unless analyzing small headwater reaches or an entire headwater watershed. 

* Open the [National Map Viewer](https://apps.nationalmap.gov/viewer/) in a web browser. 
* In the National Map Viewer, zoom to the extent of the project study area. 
* From the toolbar, open the `Layer List` panel. 
* On the `Layer List` panel, toggle-on the visibility of the `National Hydrography Dataset` (NHD).
* Under the `National Hydrography Dataset`, toggle-off the visibility of all other NHD datasets except the `Flowline - Large Scale` and `Flowline - Small Scale` layer. 
* On the `Layer List` panel, toggle-on the visibility of the `Watershed Boundary Dataset` (WBD). 
* While zoomed to the extent of your project area `NHD_Flowline` feature class, identify the smallest scale WBD Hydrologic Unit (HU) feature that defines the headwaters of your project area reach. For most small streams, this is typically a HUC12, while medium size streams may require multiple HUC12 watersheds or a possibly a HUC10 watershed. 
* From the toolbar, open the `Select` panel. To begin, make all layers unselectable. 
* Scroll down to the `xx-digit HU (xxx)` layer (based on the HU you identified in the previous step) and check the box to select features from this layer. 
* In the map panel, draw a rectangle around the extent of the WBD HUs that represents the upstream drainage area of your project reach. 
* On the `Select` panel, click the "three dot" menu of the `xx-digit HU (xxx)` layer chosen. Select the `Export to GeoJSON` option and save the export file in the `ProjectName_Year1` folder. 
* In ArcGIS Pro, use the `JSON to Features` tool to convert the exported WBD HU JSON features into the `ProjectName_Year1.gdb` file geodatabase. 
* Use the Data Management `Project` tool to project (verb) the imported WBD HU features to the chosen project (noun) coordinate system. Name the re-projected feature class `WBD_HU`. 


## Acquire Contributing Area Watershed Elevation Model
The purpose of this step is to acquire an existing, pre-made DEM of the entire study area contributing watershed. This DEM will help determine the following parameters:

* Determine if an existing, pre-made DEM will serve for this FluvialGeomorph analysis. 
* Derive high resolution project study area watershed extents.
* Calculate reach scale drainage area. The coverage of this DEM should cover the entire upstream contributing watershed of the study area. 

**Multiple LiDAR Surveys**   
Since the study area watershed boundaries are unlikely to have changed between LiDAR surveys, it is unnecessary to acquire the entire watershed elevation model for LiDAR survey dates prior to the [base year](#units_of_analysis). Only the watershed elevation model representing the base year needs to be acquired. 

* Open the [National Map Viewer](https://apps.nationalmap.gov/viewer/) in a web browser. 
* Click the "Data Download" link at the top of the map viewer. This will open the [TNM Download app](https://apps.nationalmap.gov/downloader/#/). 
* In the [TNM Download app](https://apps.nationalmap.gov/downloader/#/), in the map panel, zoom to the extent of the project study area. 
* On the `Datasets` tab, under the `Data` section, check the box next to the `Elevation Products (3DEP)`. Choose the `1 meter DEM` option. 
* Under the `Area of Interest` section, choose the `Polygon` tool, and in the map panel draw a polygon that covers the `WBD_HU` feature class created in the previous step.  
* Under the `Advanced Search` section, click the `Search Products` button. This will display a set of search results on the `Products` tab. 
* Mouse-over each of the returned datasets to verify the areal coverage and collection date. Only the most recent survey date is needed. 
* Determine which datasets are needed for full coverage of the project study area. Click the `Add to Cart` button to add the required datasets to your cart. 
* On the `Cart` tab, use the download link to download each dataset individually if there are only a small number of datasets. 
* If there are many DEMs to download, use the [`uGet Download Manager`](https://ugetdm.com/downloads/windows/) app to automate the download process. Use the `CSV` button to download a .csv file of the cart items. Use `uGet` to process the .csv file to complete the download. 

### Mosaic pre-made DEMs
The purpose of this step is to combine the pre-made, coarse-scale DEMs into a single DEM covering the project study area contributing watershed area. 





### Determine if the pre-made DEM has sufficient resolution
### Verify that the DEM elevations are in feet
### Create a hillshade to improve visualization

## Develop High Resolution Elevation Model
The purpose of this DEM is to derive a detailed stream terrain model that meets the resolution requirements of the study. 

### Download LiDAR point cloud data
### Build a DEM from LiDAR point cloud data
### Verify that the DEM elevations are in feet
### Create a hillshade to improve visualization


