# Level 1 Workflow
This chapter describes the workflow steps necessary to complete a Level 1 FluvialGeomorph analysis. 

## Create Terrain
The purpose of this stage is to develop the terrain models for the project study area for all available LiDAR surveys. 

### Define Study Area
The purpose of this step is to define the location and extent of the study area.  

#### Create a Study Area Geodatabase
The purpose of this step is to create a new study area geodatabase to store the project study area data. This step will need to be repeated for each [LiDAR survey](#units_of_analysis) that exists for this project study area. Since three LiDAR surveys exist for the project study area, three geodatabases will need to be created:

* Papillion_Creek_2016.gdb
* Papillion_Creek_2010.gdb
* Papillion_Creek_2006.gdb

The elevation data for each LiDAR survey will be processed separately and a synthetic stream network will be derived for each LiDAR survey independently. Begin processing the data for the [base year](#units_of_analysis) first, then work backward in time to process earlier LiDAR surveys in reverse chronological order. Several analysis steps require the base year data to be processed first. For some tools, surveys prior to the base year use the base year data as inputs. This is done to express earlier surveys in terms of the base year for comparison purposes. 

* Create a new folder on a local workstation drive. Name it for the project study area. 
* Within this project folder, create a new study area file geodatabase. Name it for the study area. 
* If there are multiple LiDAR surveys, add a date suffix to the geodatabase name.  
* Choose a coordinate system for this project. You will use this coordinate system for all vector datasets created for this project. It is the analyst's responsibility to ensure that each vector dataset in this project uses this coordinate system. The only exception to this requirement are raster DEMs (which may use another coordinate system).  



#### Define the Longitudinal Extent of the Study Area
* Use the [USGS National Hydrography Dataset(NHD)](https://www.usgs.gov/core-science-systems/ngp/national-hydrography/national-hydrography-dataset) High Resolution to define the longitudinal extent of the reaches of the study area. 
* Import the NHD Flowline feature class to represent the study area reaches. 
* These will be used only as an initial coarse-scale representation of the study reaches to facilitate early study area definition. This study will derive high resolution definitions of study reaches. 
* Edit the extent of the NHD Flowline feature class into a set of initial study area reaches.   

#### Define the Areal Extent of the Study Area. 
* Create a new polygon feature class named `study_area`. 
* This polygon should outline the extent of the study reaches. 
* If the study reaches are already known, sub divide the `study_area` polygon into these study reaches. 
* This polygon should define the "must-have" extent for both communicating the study area, as well as helping to define the area to acquire elevation data.  

#### Determine the Contributing Watershed to the Study Area
* Use the [NRCS Watershed Boundary Dataset (WBD)](https://www.nrcs.usda.gov/wps/portal/nrcs/main/national/water/watersheds/dataset/) to define the upstream contributing watershed of the study reach. 
* Depending on the scale of the study reach, identify the relevant hierarchical levels to characterize the study area. 
* Import these Hydrologic Unit Code (HUC) polygons into the study area geodatabase. 


### Acquire Study Area Watershed Elevation Model
The purpose of this step is to acquire an existing, pre-made DEM of the entire study area watershed. This DEM will help determine the following parameters:

* Determine if an existing, pre-made DEM will serve for this analysis. 
* Derive study area watershed extents.
* Calculate reach scale drainage area. The coverage of this DEM should cover the entire upstream contributing watershed of the study area. 

**Multiple LiDAR Surveys**   
Since the study area watershed boundaries are unlikely to have changed between LiDAR surveys, it is unnecessary to acquire the entire watershed elevation model for LiDAR survey dates before the [base year](#units_of_analysis). Only the watershed elevation model representing the base year needs to be acquired. 

#### Identify a source of elevation data for your study area
#### Determine if the pre-made DEM has sufficient resolution
#### Verify that the DEM elevations are in feet
#### Create a hillshade to improve visualization

### Develop High Resolution Elevation Model
The purpose of this DEM is to derive a detailed stream terrain model that meets the resolution requirements of the study. 

#### Download LiDAR point cloud data
#### Build a DEM from LiDAR point cloud data
#### Verify that the DEM elevations are in feet
#### Create a hillshade to improve visualization



### Hydro Modify DEM
The purpose of this step is to create a hydro-modified DEM to ensure proper water flow across the study area. 

#### Identify Flow Blockages
The purpose of this step is to develop a [`cutlines`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#cutlines-fc) feature class representing flow blockages in the study area. 

* Examine the stream channel through the study area and determine if there are any blockages to flow in the DEM. 
* Focus only on flow blockages within the main channel of the study reaches. Flow blockages outside of the the channels of the study reaches do not need to be identified for FluvialGeomorph analysis. 
* These blockages are typically built infrastructure such as road embankments where streams are conveyed through culverts or underground storm water structures. 
* If there are flow blockages in the study area reach channels, create a new line feature class named [`cutlines`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#cutlines-fc) to store terrain modifications that remove flow blockages. This feature class must be in the same coordinate system as the DEM being modified. 
* In an edit session, identify human structures that block flow along the channel of the stream reach being studied. 
* Draw a cutline beginning at the upstream side of the blockage to a point just downstream of the blockage. 
* The start point and end point of the cutline must cover the area to be modified. 
* The downstream end of this cutline must be located in "good data", because the lowest DEM value found along this line will be used to re-assign DEM values to all DEM pixels covered by the cutline. 

#### Burn cutlines into the terrains
The purpose of this step is to remove flow blockages from the terrain. 

* Use the [`02 - Hydro DEM`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#hydro-dem-tool) tool to "burn" the [`cutlines`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#cutlines) features into the study area watershed DEM. This tool creates the [`dem_hydro`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#hydro-modified-raster) raster. Rename this DEM `watershed_dem_hydro`. 
* Use the [`02 - Hydro DEM`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#hydro-dem-tool) tool to "burn" the [`cutlines`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#cutlines) features into the high resolution DEM. This tool creates the [`dem_hydro`](https://www.techmanual.fluvialgeomorph.org/toolbox.html#dem-hydro-raster) raster. 


***

## Define Stream Reaches
The purpose of this stage is to synthetically derive from the terrain the study area reaches and their watersheds. 

### Calculate Contributing Area
The purpose of this step is to calculate the contributing drainage area for each pixel in the DEM. 

* Use the `03a - Contributing Area D8` tool to calculate the contributing area for the study area watershed. This tool creates the `contributing_area` raster. Rename this DEM `watershed_contributing_area`. 
* Use the `03 - Contributing Area` tool to calculate the contributing area for the high resolution DEM. If created, use the `dem_hydro` raster as input.  
* The `processes` parameter of the `03 - Contributing Area` tool can be safely set to approximately 2 less than the number of cores on the computer running the tool. 

### Derive Stream Network 
The purpose of this step is to derive a synthetic vector stream network from the DEM for the study area. 

* Use the high resolution DEM to derive the stream network. 
* Use the `04 - Stream Network` tool to create a synthetic stream network from the hydro-modified DEM. The `processes` parameter can be safely set to approximately 2 less than the number of cores on the computer running the tool. 
* The `threshold` parameter should be set to a value of 200,000 to 500,000 depending on the study area.  
* If the resulting `stream_network` is too dense (requiring a large amount of editing to remove extraneous tributaries), try rerunning the tool and increasing the `threshold` value. Conversely, if the resulting `stream_network` is too sparse (not enough of the stream network was delineated), try rerunning the tool and decreasing the `threshold` value.   
* Edit the resulting `stream_network` feature class to remove all tributary streams that do not constitute the network that will be analyzed in this study.   
* Edit the `stream_network` feature class to ensure that stream segments are represented by a single line and that there are no gaps in the steam network.  

### Calculate Slope and Sinuosity
The purpose of this step is to examine the stream network slope and sinuosity to help make decisions about how best to define study reaches. 

* Use the `04a - Stream Network Points` tool to convert the `stream_network` feature class into the `stream_networks_points` feature class. 

**Determine the moving window size**   
Slope and sinuosity are scale dependent metrics. This means that these metrics are affected by the size of the upstream moving window used in their calculation. To determine the appropriate size of this moving window for this study area, use the following steps:

* It is recommended that slope and sinuosity be calculated using a moving window size equal to two meander wavelengths. 
* Estimate a rough initial bankfull width for the reach. Use the DEM to examine several representative locations throughout the study area. 
* Estimate the length of two meander wavelengths by multiplying the rough bankfull width by 10 (e.g., 30ft bankfull width * 10 = 300ft, two meander wavelengths).  
* Determine how many `stream_network_points` two meander wavelengths represent. For example, if `stream_network_points` are spaced 1m apart on average, then two meander wavelengths would be 91 points (i.e., 300ft / 3.28084ft per m). 

**Calculate Slope and Sinuosity**   

* Use the `04b - Slope and Sinuosity` tool to calculate the slope and sinuosity of the `stream_network_points` feature class. 
* Set the `gradient_distance` parameter to the number of upstream `stream_network_points` that you calculated in a previous step. 
* If the elevations in the channel seem noisy, check the `use_smoothing` parameter and set the `loess_span` parameter to a value between 0-1. 

**Confirm the degree of smoothing** 

* Use a chart to verify the choice of the smoothing `loess_span` parameter. 
* Right-click on the `gradient_*` FC in the map Table of Contents and select "Create Chart", and select "Line". In the `Date or Number` dropdown, choose the field `POINT_M`. In the `Aggregation` dropdown, choose `None`. In the `Numeric field(s)` checklist, check the boxes next to `Z` and `Z_smooth`. Click the `Apply` button to view the chart.
* Visually assess the degree of smoothing. The smoothing should be high enough to eliminate LiDAR elevation noise, but not so high as to eliminate meaningful channel elevation change. 
* If the smoothing is not ideal, re-run the tool and adjust the `loess_span` parameter. 


### Define Reaches
The purpose of this step is to segment the stream network into a set of sites and reaches that can be analyzed in more detail through the remainder of the study. The `stream_network` must be sub-divided into a set of sites and reaches that meet the following requirements:

**Criteria for Creating Sites:**

* A project study area composed of several sub-watersheds will need to be divided into a set of [sites](#units_of_analysis). 
* Sites within a project area are typically named tributaries that are the next hierarchical level beneath the project. 

**Criteria for Creating Reaches:**   

* "Major" tributaries should be used to divide a site into reaches. How big of an increase in drainage area/discharge constitutes a major tributary depends on the size of the watershed and physiographic region. 
* A specific reach should contain a range of similar drainage area values. 
* Slope and sinuosity can be considered in the decision to subdivide a reach. 
* Built infrastructure may be used to divide reaches (e.g., dams, major roads). 
* Study objectives may drive the definition of reaches (e.g., economic benefits analysis, existing project reach definition). 
* The distribution of the slope and sinuosity values along the stream network may help determine the natural breaks in the stream network. 

Using the criteria chosen from the list above, use the standard ESRI edit tools to subdivide the `stream_network` feature class into a set of features representing the reaches of your study.  

* Manually edit the `stream_network` feature class to modify the geometry to create a set of features representing the study area sites and reaches.  
* Set the `ReachName` field to the value to be used to uniquely define sites and reaches throughout the remainder of the study. 
* Reach names are typically created using the site name and adding a suffix for the reach (e.g., R1, R2, etc.). 
* Site names are typically defined by the primary tributary name. 
* Be deliberate with the naming of sites and reaches as these names are used for all operations by each tool.  

### Delineate Watersheds
The purpose of this step is to delineate the areal extent of watersheds for each reach in the study area. 

* In the `stream_network_points` feature class, select points that represent the downstream location of each of the sites in the project study area. 
* Export these point features to a new feature class named `watershed_points` in the study area geodatabase. 
* Use the `04c - Watershed` tool to create a watershed polygon for each feature in the `watershed_points` feature class. 


***

## Derive Flowline
The purpose of this stage is to create a new site geodatabase, derive the site flowline, create new reach geodatabases for each reach, and copy the flowline to  each reach's geodatabase. 

### Create the site geodatabase
The purpose of this step is to create a new site geodatabase and populate it with initial data. 

* In the [study area folder](#folder_structure), begin by creating a new site folder named for the site.  
* In the new site folder, create a new "Data" folder. 
* In the new site data folder, create a new site geodatabase for each LiDAR survey. In the example above, the Papillion Creek project study area will be subdivided into a specific site called Cole Creek. Since there are multiple LiDAR surveys for this study area (e.g., 2016, 2010, 2006), three site geodatabases will need to be created.  

  * Cole_Creek_2016.gdb   
  * Cole_Creek_2010.gdb   
  * Cole_Creek_2006.gdb   

* Back in the study area geodatabase, select the features in the `stream_network` feature class representing the current site. Use the "Data | Export Features" function to export the selected site features to the new site geodatabase. Name the exported feature class `stream_network`. 
* Examine the `dem_hydro` raster and determine the maximum width of the active floodplain along the entire site. Be conservative with this estimate. Given its later use, it is important to generously overestimate this value. 
* Use this maximum floodplain width estimate to buffer the reach `stream_network` feature class and name it `stream_network_buffer`. 
* Use the ESRI `Clip Raster` tool to clip the study area geodatabase `dem_hydro` to the extent of the reach using the `stream_network_buffer` feature class. Save the clipped raster to the reach geodatabase and name it `dem_hydro_<buffer distance>` (e.g., `dem_hydro_1000` for a buffer distance of 1000 meters). 
* Use the ESRI `Clip Raster` tool to clip the study area geodatabase `contributing_area` to the extent of the reach using the `stream_network_buffer` feature class. Save the clipped raster to the reach geodatabase and name it `contributing_area_<buffer distance>` (e.g., `contributing_area_1000` for a buffer distance of 1000 meters).  
* If you discover in later steps that the buffer distance was underestimated, you will need to repeat this step with a wider buffer. 


### Create the Flowline
The purpose of this step is to derive the site flowline. The `05 - Flowline` tool converts a `stream_network` feature into a `flowline` FC. This tool smooths the `stream_network` geometry and converts the flowline into a route. 

* Use the `05 - Flowline` tool to process the site `stream_network` FC to produce a new `flowline` FC. 
* Set the `output_workspace` parameter to the site geodatabase. 
* Use a `smooth_tolerance` parameter value from 5-20. The goal is to produce a smooth flowline, but not to remove too much resolution from the line. 
* Ensure that the flowline remains in the channel and is not simplified into the floodplain. If this occurs, rerun reducing the degree of smoothing. 
* Edit the `flowline` feature class to ensure that the flowline is digitized beginning with the downstream end and digitized upstream. 
* In an edit session, select the flowline feature, choose to edit vertices, and ensure that the red endpoint is at the upstream end of the flowline. 
* If not, use the "Reverse Direction" (aka flip) command to ensure the flowline is digitized in the upstream direction.  
* It is critical that the flowline is digitized in the upstream direction. If this step is not performed, all subsequent tools will malfunction. 


### Create the Reach Geodatabase
The purpose of this step is to create a set of new reach geodatabases for each reach in a site and populate these reach geodatabases with initial data. This step will need to be repeated for each reach AND survey in the project study area [site](#units_of_analysis). For example, if a site has five reaches (e.g., R1-R5) and three LiDAR surveys (e.g., 2016, 2010, 2006), then a total of 15 reach geodatabases must be created at this stage:

2016         | 2010         | 2006 
:---         | :---         | :---
y2016_R1.gdb | y2010_R1.gdb | y2006_R1.gdb 
y2016_R2.gdb | y2010_R2.gdb | y2006_R2.gdb 
y2016_R3.gdb | y2010_R3.gdb | y2006_R3.gdb 
y2016_R4.gdb | y2010_R4.gdb | y2006_R4.gdb 
y2016_R5.gdb | y2010_R5.gdb | y2006_R5.gdb 

Table: Reach Geodatabases Required for a Site with 5 Reaches and 3 LiDAR Surveys. 

* In the [site data folder](#folder_structure), create a new reach geodatabase named for the reach. Use the `ReachName` value for the name of this new reach file geodatabase. 
* Reach names are typically created using the site name and adding a suffix for the reach (e.g., R1, R2, etc.). 
* Back in the site geodatabase, select the feature in the `flowline` feature class representing the current study reach. Use the "Data | Export Features" function to export the selected reach feature to the new reach geodatabase. Name the exported feature class `flowline`. 
* Ensure this new reach geodatabase version of `flowline` contains only one feature representing the current reach. 
* Ensure that the `ReachName` field contains the correct name for the reach. As this reach name value is used throughout the toolbox, it is extremely important to ensure this value is used consistently across all FCs for this reach. Failure to be consistent with the `ReachName` value will lead to lots of errors that are difficult to troubleshoot. Get it right from the beginning. 


### Create Flowline Points
The purpose of this step is convert the `flowline` into a series of points along the reach. The `06 - Flowline Points` tool takes the `flowline` feature class, converts it to a route, calculates the distance to the mouth of the river for all vertices, and creates a `flowline_points` feature class. 

* Use the `06 - Flowline Points` tool to convert the `flowline` feature class into a new FC named `flowline_points`. 
* Set the `station_distance` field to approximately 1 meter. 
* For a site with multiple reaches, set the `km_to_mouth` parameter for the downstream-most reach to 0. 
* Set the `km_to_mouth` parameter for each upstream reach to the upstream-most value (i.e., the highest `km_to_mouth` value of the downstream reach's `flowline_points` FC) of the downstream reach. For example, set the `km_to_mouth` of the Reach-2 `flowline_points` FC to `1.2345` if the maximum value of Reach-1's `flowline_points` FC `km_to_mouth` field is `1.2345`. 
* The goal is that longitudinal stationing within a site containing multiple reaches should be sequential and unique throughout the site (i.e., lower station values at the bottom of the site and higher station values at the top of the site). This allows reach FCs to be combined after reach-level analysis is complete. 
* The `calibration_points`, `point_id_field`, and `measure_field` parameters can be left blank when processing the [base year](#units_of_analysis).

**Multiple Surveys**   
To make LiDAR surveys collected before the [base year](#units_of_analysis) directly comparable to the base year, previous survey flowlines must be ["calibrated"](https://pro.arcgis.com/en/pro-app/latest/tool-reference/linear-referencing/calibrate-routes.htm) to the base year. This adjusts any changes in flowline planform between surveys to be expressed in terms of the base year longitudinal stationing. 

* If multiple LiDAR surveys exist for a project study area, the `flowline_points` for any previous LiDAR survey must be calibrated using the `flowline_points` of the base year. 
* For example, if 2016 is the base year, when deriving the `flowline_points` for a LiDAR survey from 2010, the base year's `flowline_points` (2016) must be used for the `06 - Flowline Points` tool's `calibration_points` parameter value. 
* Set the `point_id_field` and `measure_field` parameters to the fields in the base year's `flowline_points` FC. 
* Set the `search_radius` parameter to the maximum distance between the `flowline` of the current survey and the base year `flowline`. 


***

## Define Initial Floodplain and Channel Extent
The purpose of this stage is to define the initial floodplain and channel extent, for each reach and survey event. 

### Detrend DEM
The purpose of this step is to produce a detrended DEM. A detrended DEM normalizes stream bank elevations for a specific reach. 

* Inspect the reach to determine the width of the active floodplain. Use the measure tool to measure from the `flowline` outward to the widest extent of the active floodplain. This value will be used as the `buffer_distance` value in the following step.  
* Use the `07 - Detrend` tool to create a detrended DEM for the study reach. Set the `buffer_distance` field to a distance wide enough to capture the reach's entire active floodplain.  

### Estimate Initial Channel Extent 
The purpose of this step is to use the detrended DEM to visually extract an initial channel extent polygon. The `detrend` DEM created in the last step can be used to iteratively explore different inundation extents derived from various water surface elevations.  

* Add the `detrend` feature class to the map Table of Contents. Name this layer `Channel Extent`. 
* On the Symbology tab of the `Channel Extent` layer, use the Classified renderer to classify the raster into 2 classes. Set the first class boundary to the detrended elevation that you would like to explore. Set the color of the first class (min value - detrended elevation) to blue and the color of the second class (detrended elevation - max value) to No Color. 
* Set the transparency of the `Channel Extent` layer to 50%. 
* Begin to delineate the channel extent by selecting a detrended elevation that inundates the channel up to at least the first terrace. The goal at this stage is to select a detrended elevation that captures the extent of the channel without "spilling" too much water into the floodplain. Once you discover which detrended elevation begins to allow water to access the floodplain, reduce the detrended elevation value slightly to keep the water in the channel. Try several detrended elevation values to help make the decision. 
* When you have chosen a detrended elevation, use the `08 - Water Surface Extent` tool to extract an initial channel extent area polygon. This tool creates a new polygon feature class named `banks_raw_xxx`, where xxx is the detrended elevation selected. 
* This feature class must be edited to select the channel area polygon(s). Open the attribute table for the `banks_raw_xxx` feature class and use advanced sorting to sort first by `gridcode` and then by `Shape_Area`. Polygons with `gridcode` = 1 are polygons inundated at the detrended elevation. Typically, the polygons with the largest area represent the channel. Begin selecting `gridcode` = 1 polygons with the largest area until the entire channel area is selected. 
* Export these selected features to a new feature class named `initial_channel_extent`. 
* Delete the `banks_raw_xxx` feature class created in this section.

### Create the Initial Channel Mask layer
The purpose of this step is to create a layer that defines an area just beyond the initial channel extent.  

* Add the `detrend` feature class to the map Table of Contents. Name this layer `Channel Mask`. 
* In the symbology of this layer, change the renderer from `stretched` to `classified`. Set the number of classes to 2. In the `classification` dialog, set the break value between the two classes to about one to two feet higher than the initial bankfull extent estimate. A couple of feet above the initial bankfull extent estimate should define the extent of the just the channel. For example, if the initial bankfull extent was estimated at 102 detrended feet, the initial bankfull height estimate would be 2 feet. One foot higher than the 2 foot initial bankfull height estimate would therefore be 103 detrended feet. 
* Set the transparency of the `Channel Mask` layer to 50%. 

### Estimate Initial Floodplain Extent
The purpose of this step is to create a layer that defines the an initial estimate of the floodplain inundation extent. 

* Add the `detrend` feature class to the map Table of Contents. Name this layer `Floodplain Mask`. 
* In the symbology of this layer, change the renderer from `stretched` to `classified`. Set the number of classes to 2. In the `classification` dialog, set the break value between the two classes to four times the initial bankfull extent estimate. Four times the initial bankfull extent estimate should define the extent of the active floodplain. For example, if the initial bankfull extent was estimated at 102 detrended feet, the initial bankfull height estimate would be 2 feet. Four times the 2 foot initial bankfull height estimate would therefore be 108 detrended feet. 
* Set the transparency of the `Floodplain Mask` layer to 50%.  

### Calculate Channel Slope Raster
The purpose of this step is to create a channel slope raster that can be used in the visual identification of riffle locations in following step. 

* Use the `09 - Channel Slope` tool to calculate a raster of the channel slope. Use the `intitial_channel_extent` polygon created earlier to define the channel area within which the slope raster will be calculated. This tool creates a new feature class named `channel_slope`. 

### Create Initial Centerline
The purpose of this step is to create a stream centerline. The centerline represents the rough midline of the stream between the banklines.  

* Use the `10 - Centerline` tool to create a `centerline` polyline feature class representing the stream midline at the estimated bankfull water surface elevation using the `initial_channel_extent` feature class. 


***

## Create Regular Cross Section Geometry
The purpose of this stage is to create regularly spaced stream cross sections and extract terrain-derived hydraulic parameters for each reach and survey event. 

### Create Regular Cross Sections
The purpose of this step is to create regularly spaced cross sections along each reach.  

* The goal of this step is to create a set of regularly spaced cross sections that well represent the channel conditions found in this reach. 
* Determine the typical maximum distance from the reach `flowline` to the edge of the active floodplain. The goal is not to identify the maximum distance to the edge of the floodplain, but to identify the typical distance to the edge of the floodplain. 
* Determine the spacing between cross sections necessary to represent conditions along this stream. Cross section spacing for small stream of 50-100 feet works well. Larger rivers do not require such tight spacing. 
* Use the `11 - XS Layout` tool to create a set of regularly spaced cross sections (referred to as transects in this tool). Use the values determined in the previous steps to set this tool's parameters. 
* For a site with multiple reaches, regular cross sections must be uniquely numbered across all reaches. The `Seq` field values of regular cross sections should not repeat within the reaches of a site. 
* The downstream-most cross section in the site should be numbered starting with the `Seq` field value of 1 and increase moving upstream. 
* The `11 - XS - Layout` tool automatically numbers regular cross sections `Seq` values starting with the value 1 at the downstream-most cross section.  
* Use the `13a - XS Resequence` tool to set the starting `Seq` value for each reach.  
* For all reaches other than the first reach (downstream-most) in a site, the cross sections must be re-sequenced using the `13a - XS Resequence` tool. 
* Set the `Seq` field value for each upstream reach to the upstream-most value (i.e., the highest `Seq` value of the downstream reach’s regular cross section FC) of the downstream reach. 
* For example, set the `Seq` of the Reach-2 regular cross section FC to 58 if the maximum value of Reach-1’s regular cross section FC `Seq` field is 57.

### Calculate Cross Section Watershed Area
The purpose of this step is to calculate the watershed area for each regularly spaced cross section. 

* From the study area geodatabase, use the `watershed_contributing_area` raster that covers the entire contributing watershed of the study area.    
* Use the ERSI `Clip Raster` tool to clip the `watershed_contributing_area` raster to `stream_network_buffer` to speed tool run time. 
* Add the `contributing_area_buffer` raster to a map and symbolize with a “hot-cold” stretch renderer.
* Add the `flowline` and regular cross section features classes to the map. Place them on top of the `contributing_area_buffer` raster. 
* Determine the maximum distance from the intersection of each cross section and the `flowline` to the nearest pixel of high flow in the `contributing_area_buffer` raster. This value will be used for the `snap_distance` in the next step. 
* Use the `12 - XS Watershed Area` tool to calculate the watershed area for each cross section. 
* For the `flow_accum` parameter, use the `contributing_area_buffer` raster. 
* For the `snap_distance` parameter, use the distance you calculated in a previous step.

### Calculate Cross Section River Position
The purpose of this step is to calculate the river position for each regularly spaced cross section. 

* Use the `13 - XS River Position` tool to calculate the distance to the mouth of the river for each cross section. 
* The river position of each cross section will be used in later steps to calculate several channel parameters (i.e., gradient, sinuosity). 

### Calculate Cross Section Points
The purpose of this step is to convert each cross section into a set of evenly stationed points and assign DEM and detrended elevation values. 

* Use the `14 - XS Points` tool to calculate cross section station points for each cross section. 
* The `station_distance` parameter should be set to approximately the resolution of the DEM. For example, if the DEM has a cell size of 1 foot (0.3048 meter), set the `station_distance` to that distance (using the linear units of the coordinate system used for the project's vector data). 
* This tool creates a new feature class named `<cross section FC name>_points`. 


### Calculate Cross Section L1 Dimensions
The purpose of this step is to calculate the L1 dimensions for the regularly spaced cross sections. 

**Determine the moving window size**    
Many stream metrics are scale dependent, meaning these metrics are affected by the size of the moving window used in their calculation. To determine the appropriate size of the moving window for this reach, use the following steps:

* Many stream metrics are typically calculated using a moving window size equal to two meander wavelengths (one upstream meander wavelength and one downstream meander wavelength). 
* Using the initial `Channel Mask` layer that you created earlier, estimate the typical bankfull width for the reach. 
* Estimate the length of two meander wavelengths by multiplying the bankfull width estimated in the last step by 10 (e.g., 30ft bankfull width * 10 = 300ft, two meander wavelengths).  
* Determine how many cross sections two meander wavelengths represent. For example, if regular cross sections are spaced 100ft apart, then two meander wavelengths would be 3 cross sections (i.e., 300ft / 100ft between cross sections). 

**Calculate L1 Dimensions**   

* Use the `15a - XS Dimensions, Level 1` tool to calculate L1 dimensions. 
* Set the `xs_fc` parameter to the regular cross sections FC you created in a previous step. 
* Set the `lead_n` parameter to the number of upstream cross sections that you calculated in a previous step. 
* If the elevations in the channel seem noisy, check the `use_smoothing` parameter and set the `loess_span` parameter to a value between 0-1. 
* Confirm that the `vert_units` of the DEM are in feet. 

**Confirm the degree of smoothing**   

* Use a chart to verify the choice of the smoothing `loess_span` parameter. 
* Right-click on the `*gradient_**_dims_L1` FC in the map Table of Contents and select "Create Chart", and select "Line". In the `Date or Number` dropdown, choose the field `POINT_M`. In the `Aggregation` dropdown, choose `None`. In the `Numeric field(s)` checklist, check the boxes next to `Z` and `Z_smooth`. Click the `Apply` button to view the chart.
* Visually assess the degree of smoothing. The smoothing should be high enough to eliminate LiDAR elevation noise, but not so high as to eliminate meaningful channel elevation change. 
* If the smoothing is not ideal, re-run the tool and adjust the `loess_span` parameter. 


***

## Identify Infrastructure
The purpose of this stage is to identify salient features in the floodplain that may be affecting channel hydraulics along each reach. Here are some ideas for the features you should identify:

* Significant tributaries
* Built infrastructure
* Significant geologic features


### Create Features
The purpose of this step is to identify the longitudinal position of noteworthy stream features for graph and map labeling. 

* Create a new point FC named `features` containing the following fields:
    * `Name` - Text (50), Used to record the name of the river feature. 
    * `km_to_mouth` - double, Used to record the feature's longitudinal position within the reach. 
* Working upstream from the downstream end of the reach, examine the DEM and aerial imagery for significant river features and built infrastructure that could potentially impact stream structure and function.
* Add the `flowline_points` feature class to the current map. 
* Set the display field to the `km_to_mouth` field. 
* Create a `features` point feature centered along the `flowline` FC. 
* Assign it a descriptive label in the `Name` field, and record its longitudinal position along the reach (see next bullet) in the `km_to_mouth` field. 
* To determine a feature's longitudinal position along the reach, use the identify tool to find the closest point in the `flowline_points` feature class and use the value from its `POINT_M` value. 
* Repeat these steps to record all of the significant features along each reach. 


***

## Run Report
The purpose of this stage is to run the Level 1 report for each reach. 

### Run the Level 1 Report
The purpose of this step is to run the L1 report for each reach. The Level 1 Report displays the channel dimensions for the base year, compared with multiple previous year surveys. 

* In the Reports toolset, use the `Level 1 Report` tool to produce the Level 1 Report. 
* For the `stream` parameter, use the value of the `ReachName` field used in the `flowline` FC. 
* For the `flowline_fc` parameter, enter the `flowline` FC for the base year survey. 
* For the `xs_dimensions_fc` parameter, use the `*_dims_L1` FC calculated for the regular cross sections of the base year. 
* The `flowline_points_*` parameters should be entered with the FC for the most recent survey first (i.e., the base year) and then the previous surveys in reverse chronological order (e.g., 2016, 2010, 2006). 
* The `xs_points_*` parameters should be entered with the FC for the most recent survey first (i.e., the base year) and then the previous surveys in reverse chronological order (e.g., 2016, 2010, 2006). 
* The `survey_name_*` parameters are used to label the surveys in maps and graphs. 
* The FCs and labels used for the `flowline_points_*`, `xs_points_*`, and `survey_name_*` parameters must be entered in the same order (e.g., 2016, 2010, 2006) in each set of numbered parameters. 
* For the `features_fc` parameter, enter the `features` FC for the base year survey. 
* For the `dem` parameter, enter the DEM for the base year survey. 


### Perform QA
The purpose of this step is to use the QA Checklist to verify the reports have run correctly and identify any data mistakes that need to be corrected.

* Follow the instructions in the QA Checklist Chapter, [Level 1 Report](#L1_report_qa), to verify that the reports have run correctly. 
* Make the required changes suggested in the QA Checklist and rerun the report. 
* Repeat these QA iterations until the reports are correct. 


***

## Determine Next Steps
The purpose of this step is to determine what further steps need to be taken. 

* Review the results of the Level 1 Report and determine if the project goals require proceeding to developing the Level 2 analysis. 


***
