# Report QA Checklist {-}
This chapter describes the items an analyst needs to check to ensure that the FluvialGeomorph tools have run correctly to produce clean reports. In addition to following the guidance in the previous chapters when preparing the data and running each tool, this chapter will provide a checklist of items you'll need to verify after each report completes. Reports are the place where all your hard work comes together! Your work is not complete just because the tools run without any errors. A lot of datasets must work together to make these reports come out cleanly. Because these reports integrate so many individual datasets, many issues aren't discovered until you run the reports. This checklist will help you identify where things might not be exactly right with previous tool runs and what you'll need to do fix them. 

## Level 1 Report

### Section: Study Area Overview
This report section contains a set of reach overview maps drawn using the flowline and the cross section dimensions, _dims_L1, feature classes (fc). Both the aerial photo and elevation are provided by [Mapbox Raster Tiles](https://docs.mapbox.com/api/maps/#raster-tiles). 

#### Check the stream name
All of the tools depend on consistent reach naming! Ensuring consistent naming begins with deriving the flowline fc. The ReachName field must contain the same value for all of the fc's within a reach geodatabase. This is the single biggest gotcha we find running these tools. If tools aren't working correctly and you're sure you've done everything else right, consistent stream names is the first thing to check!

#### Cross section labels at the correct interval

#### Cross sections cover the full extent of the flowine

#### Map background displaying correctly


### Section: Longitudinal Profile
This report section contains two longitudinal profile graphs, one drawn using the **flowline_points** fc, and the second is drawn using the cross section dimensions,  **_dims_L1** fc. 

#### Elevation values are reasonable

#### Elevation ranges are similar between surveys

#### Multiple surveys are labeled correctly

* Most recent survey listed at the top, with earlier surveys listed below. 
* Survey date indicate the date flown (e.g., not the contract date). 

#### Multiple surveys are calibrated to the base year

#### Stationing in the correct units

#### Stream feature labels display correctly



### Section: Cross Section Metrics
This report section contains a Level 1 cross section metrics plot drawn using the cross section dimensions fc, **_dims_L1**. 

#### Cross section watershed area calculated correctly

* Watershed values are reasonable. 
* Watershed area must decrease moving upstream. 

#### Elevation smoothing is acceptable

#### Slope values are smooth and reasonable

#### Sinuosity values are smooth and reasonable



### Section: Cross Section Profiles
This report section contains a cross section map and a cross section profile graph for each cross section in the reach. The map is drawn 

#### Cross section must be digitized from left to right

#### Cross section perpenduicular to the channel

#### Cross section covers the channel extent

#### Cross section extends onto floodplain

#### Cross section not located on built infrastructure

#### Cross section drawn within the DEM extent

#### Cross section y-axis range is not too large

#### Cross section x-axis range is not too large



## Estimate Bankfull Report



### Correct regions included

### Adequate range of bankfull elevations

### Detrended bankfull elevation set to a reasonable value




## Level 2 Report



## Level 3 Report



