# Summary
The concluding chapter is the last chapter in the main body of the report
before the reference list. The title and content may vary depending on the
project type and audience. The chapter is usually called “Summary,” “Conclusions,” or “Conclusions and Recommendations.”

A technical report may conclude with a summary chapter if its purpose is
to document empirical observations or straightforward research findings
such as the results of a field demonstration or a laboratory test series. A
summary typically reviews the research results in more detail than the abstract.

A chapter of conclusions differs from a summary chapter in that it presents
or reviews the author’s technical interpretation of the research results.
Conclusions concisely help the reader to understand how the research
objective was met and what the results mean in terms of the Army problem described in the background section. Conclusions should be included
for every secondary objective stated in the introductory chapter.

Most reports will include recommendations for the project sponsor. Recommendations generally will pertain to (1) how the research product or
results should be used to address the problem defined in the first chapter
or (2) what the sponsor may do to transition a technology product into advanced
development, field demonstration, or commercialization. 


***
