## Glossary {.unnumbered}

### A

**Aggradation**: The geologic process by which stream beds, flood plains, and the bottoms of other water bodies are raised in elevation by the deposition of material that was eroded and transported from other areas. Typically a stream that is undergoing aggradation over a long section of its length has an excess supply of sediment. Aggradation is the opposite of degradation.  

**Alluvial Stream**: A stream whose channel boundaries are composed of appreciable quantities of the sediments transported by the stream flow.  An alluvial stream is free to adjust its dimensions of size, shape, pattern, and slope in response to changes in flow and sediment.

**Alternate Loops**: A meandering channel is formed by a series of alternating changes in direction, or bends. Relatively straight reaches of alluvial rivers rarely occur in nature. Streams meander within the banks of a straight section of the stream creating loops. Over time the alternating changes cause loops and bends to change positions.

**Apex Loops**: The outermost point of the bend, where the stream reach is at its maximum distance from the central axis of the valley or the straight-line axis of the channel. It is the point of the highest curvature within the meander loop, often characterized by severe erosion, the deepest channel depth (thalweg), and the formation of a cut bank. 

### B

**Bank**: (1) The side slopes of a channel between which the streamflow is normally confined at flows up to and including bankfull discharge. (2) The side of the stream on the observer's right or left when facing downstream, either "right bank" or "left bank", sometimes called "right descending bank" or "left descending bank". Unfortunately, cross-sections of the channel are sometimes recorded, plotted, and entered into hydraulic computational programs without regard to this convention. Therefore, one must be certain of the convention being used in a particular case. 

**Bank Height Model**: Identifies the bankfull elevation - the point where water fills the channel and begins to access its floodplain - to assess stream bank stability, erosion risk, and flood capacity.

**Bankfull Discharge**: (1) The expression, "bankfull discharge," Qbf, should be used to refer to the maximum discharge that the channel can convey without overflow onto the floodplain. Although this definition, proposed by Copeland et al. (2001), differs from that used by others (e.g., Rosgen, 1996), it eliminates confusion. Theoretically Qbf and Qeff are generally equivalent in channels that have remained stable for a period of time, thus allowing the channel morphology to adjust to the current hydrologic and sediment regime of the watershed (e.g., Pickup, 1976, Andrews, 1980, Soar, 2000, but see Emmitt & Wolman, 2001). In such a channel, the bankfull discharge corresponds to a sharp change in the slope of the rating curve.  It must be noted, however, that in an unstable channel that is adjusting its morphology to changes in the hydrologic or sediment regime, Qbf can vary markedly from Qeff. Therefore, the expression "bankfull discharge" should never be used to refer to Qri or Qeff. The relationship of Qbf to Qri and Qeff is useful as an indicator of channel stability and evolution (Schumm et al., 1984; Simon, 1989, Thorne et al., 1996). The Qbf from ‘template’ or ‘reference’ reaches (stable reaches from similar watersheds) has been used as a guideline for relevant dimensions of the restored channel (Rosgen, 1996). Field indicators of Qbf are often unreliable (Williams, 1978). Problems associated with basing design on Qbf are discussed by FISRWG (1998) and Biedenharn et al. (2000) [E-SenSS] (2) Bankfull Discharge (Qb) The maximum discharge which can be contained within the channel without over-topping the banks.  Leopold et al. (1964) proposed that it is this flow which is responsible for forming and maintaining the morphology of the channel.  Bankfull stage refers to the water surface elevation during bankfull flow and can be identified from various criteria. [Watson et al. 1999]. 

**Bankfull Stage/Elevation**: (1) Same as bankfull elevation, the stage or water surface elevation at which water overflows the bankfull channel, and begins to spill onto a stream's active floodplain. The bankfull channel just conveys the bankfull, or channel forming discharge. In many streams the bankfull discharge has a recurrence interval of 1.5 to years. Indicators of the bankfull stage/elevation may include the top of a point bar, a change in vegetation, a change in the slope, the top of an undercut slope, a change in particle size, drift lines and water marks. One of the best indicators of bankfull stage is the floodplain.  (2) The water surface elevation attained by the stream when flowing at the bankfull discharge, when it is at the point of overtopping the banks at a given location. The local gage may be referenced to an arbitrary datum. 

**Bankfull Width**: (1) The width of a river or stream's bankfull channel. The bankfull channel just conveys the bankfull, or channel forming discharge. In many streams the bankfull discharge has a recurrence interval of approximately 1.5-2 years.  Indicators of the bankfull width may include the top of point bars, changes in vegetation, changes in slope, the top of undercut slopes, changes in particle size, drift lines, and water marks.  (2)  The width of a river or stream channel between the highest banks on either side of a stream. (3) The width of the water surface when a stream is at bankfull stage. 

**Bankline**: The boundary or edge where the terrestrial bank slopes down to meet the aquatic stream bed.

**Bathtub Assumption**: Method of modeling flood risk or water level rise where water is assumed to spread out uniformly over a landscape as a flat, level pool, similar to how water fills a bathtub.

**Bathymetry**: The measurement of ocean depths and the charting of the topography of the ocean floor.  The equivalent term "hydrographic survey" is often used for rivers, streams, and lakes, and refers to surveying and mapping that part of the water body which is underwater at the time of the survey. 

**Bed**: (1) The bottom of a channel.  (2) The floor or bottom on which any body of water rests. (3) In geology, a seam or deposit of mineral, also the smallest division of a stratified series. 

**Bend**: A change in the direction of a stream channel.

**Braided River**: A wide and shallow river whose flow passes through a number of interlaced branches that divide and rejoin and are separated by bars and shoals.

### C

**Centerline**: The midpoint between the left and right banks.

**Channel**: A natural or artificial waterway that continuously or periodically contains moving water.

**Conveyance**: The ability of the stream to transport water.  Often expressed numerically, with the most well-known relationships being Manning's formula or Chezy's formula, which both  use an estimated value of channel "roughness" along with the cross-sectional area of flow and the hydraulic radius to obtain a numerical value for a given location.

**Crossing**: The relatively short and shallow reach of a stream where the thalweg crosses from one bank to the other, either between bends or between pools in a straight reach. 

**Crossover**: (1) The point of inflection in a meander. The point where the thalweg intersects the center line of the stream in crossing from near the outside of the next bend. (2) The point of inflection in a meander where the thalweg intersects the centerline of the stream.  Also known as a riffle.

**Cross-Section**:  A diagram or drawing of a channel, made approximately perpendicular to the channel and/or flow direction, that defines the banks, bed, and water surface. Also may refer to the physical location of the cross-section on the ground.

**Culvert**: A buried pipe, conduit, drain or channel crossing undera road through which a stream passes.

### D
**Degradation**: (1) The geological process by which streambeds and floodplains are lowered in elevation by the removal of material; the opposite of Aggradation. (2) The geological process by which streambeds are lowered in elevation and streams are detached from their floodplain.  Also referred to as entrenched or incised streams. (3) A progressive lowering of the channel bed due to scour.  Degradation is an indicator that the stream’s discharge and/or sediment load is changing. (4) A decrease in value for a designated use. (5) The lowering of a relatively long reach of channel bed due to scour, usually caused by a lowering of the base level, a reduction in the size or quantity of sediment entering the reach, or, more rarely, a long-term increase in discharge. Degradation can occur along an entire stream length, a certain reach of a stream, (i.e. downstream of a dam, reservoir, or other sediment retention structure), or system wide (every stream in the watershed is undergoing degradation). 

**Deposition**: The settlement or accumulation of material out of the water column and onto the stream bed or floodplain.  Occurs when the energy of flowing water is unable to transport sediment load. 

**Detrend**: 

**Digital Elevation Models (DEMs)**: 

**Discharge**: (1) Discharge or streamflow, is the rate at which a volume of water flows past a point over some unit of time.  In SI system, it is expressed in m3/s.  It is normally symbolized by Q. Also expressed by ft3/s, million gallons/day, gallons/minute, or seconds/minute/day. (2) Rate of flow expressed in volume per unit of time, for instance, in cubic feet per second or liters per second.  Discharge is the product of the mean velocity and the cross-sectional area of flow. Also, see stream discharge or sediment discharge. (3) The volume of water passing through a cross-section in a stream per unit time.  It is usually expressed in cubic meters or cubic feet per second. 

**Dynamic Range Adjustment (DRA)**: 

### E

### F

**Fill**: (1) (Geology) Any sediment deposited by any agent such as water so as to fill or partly fill a channel, valley, sink, or other depression. (2) (Engineering) Soil or other material placed as part of a construction activity. 

**Floodplain**: (1) A strip of relatively smooth land bordering a stream channel that is typically overflowed (inundated) during periods of high water. Although a floodplain is generally composed of finer material near the surface than at the base, the particle size gradation is not universal.  Floodplains are generally formed by the progressive channel migration and deposition from overbank flows and are built and rebuilt by the stream in its present hydrologic regime. (2) Land built of sediment that is regularly covered with water as a result of the flooding of a nearby stream. (3) The flat area adjoining a river channel constructed by the river in the present climate and overflows during moderate flow events. (4) Low-lying areas of land adjacent to the stream that are inundated by water from the stream whenever the stream overflows its banks. Floodplains are sometimes delineated by the areas inundated during a flood with a specific reoccurrence interval, e.g. the 100-year floodplain. 

**Floodprone Area**: Generally includes the active floodplain and the low terrace. The elevation of the floodprone is qualitatively defined as 2 times the max. bankfull depth. 

**Flow**: (1) The movement of a stream of water and/or other mobile substances from place to place; Synonymous with Discharge. (2) The movement of water, and the moving water itself; (3) The volume of water passing a given point per unit of time. (4) The amount of water passing a particular point in a stream or river, usually expressed in cubic feet per second (cfs). (4) A term used to define the movement of water, silt, sand, etc.; discharge; total quantity carried by a stream. 

**Flow Accumulation**: 

**Flowline**: The idealized path followed by particles of water. 

**Fluvial**: (1) Migrating between main rivers and tributaries; (2) Of or pertaining to streams or rivers or produced by stream action. (3)(a) Pertaining to streams or rivers. (b) Of, relating to, or living in a stream or river. (c) Caused by the action of flowing water. 

### G

**Geologic Controls**: Natural geologic formation (erosion-resistant clay, stone, bedrock) that either temporarily or permanently controls the grade of a stream. 

**Geomorphology**: (1) The branch of geology that deals with the origin and nature of landforms.  The active forces that shape landforms are water, ice, wind, and gravity. (2) A branch of both physiography and geology that deals with the form of the earth, the general configuration of its surface, and the changes that take place due to erosion of the primary elements and the buildup of erosional debris. (3) That branch of both physiography and geology that deals with the form of the earth, the general configuration of its surface, and changes in the landscape that take place due to erosion, mass wasting, glaciation, subsidence, and other surficial processes.  

**Geospatial**:

### H

**Hydraulic Modelling**: 

**Hydraulic Radius**: (1) The cross sectional area of a stream divided by the wetted perimeter. For practical purposes in natural streams, equivalent to average depth unless the stream is unusually deep and narrow. (2) The cross sectional area of a stream of water divided by the length of that part of its periphery in contact with its containing conduit.  

**Hydro Modification**: 

### I

### J

### K

### L

**LiDAR**: 

**Longitudinal Profile**: (1) A graph of the vertical fall of the stream bed or water surface measured along the course of the stream; a graphical presentation of the elevation versus distance, as in channel cross sections and longitudinal sections; in open-channel hydraulics, a plot of water-surface elevation against channel distance. (2) A profile of a stream or valley, drawn along its length from source to mouth; it is the straightened out, upper edge of a vertical section that follows the winding of the stream or valley. (3) A graph of the bed (thalweg) elevation (y-axis) of a stream versus the length of the stream (x-axis).  

**Longitudinal Survey**: 

### M

**Mainstem**: (1) The principal trunk of a river or a stream. (2) The principal channel of a drainage system into which other smaller streams or rivers flow. 

**Meander**: (1) A winding stream channel, usually in an erodible alluvial valley; (2) a reverse of an S-shaped curve or series of curves formed by erosion of the concave bank, especially at the downstream end, characterized by curved flow and alternating shoals and bank erosions. Meandering is a stage in the migratory movement of the channel, as a whole, down the valley. (3) A series of sine-generated curves characterized by curved flow and alternating banks and shoals. (4) A reach of stream with a ratio of channel length to valley length greater than 1.5.  By definition, any value exceeding unity can be taken as evidence of meandering, but 1.5 has been widely accepted by convention. (5)  n. One of a series of sinuous curves, bends, or loops, developed in a flood plain by flowing water. (6) v. To change course in a sinuous, and somewhat systemic, pattern.

**Mesic**: (1) Characterized by a moderate amount of moisture. (2) Moderately wet.

### N

### O

### P
**Peak Flow**: (1) The highest discharge recorded over a specified period of time.  Often thought of in terms of spring snowmelt, summer, fall, or winter rainy season flow.  Also called maximum flow. (2) Maximum momentary stage or discharge of a stream in flood; Design discharge. 

**Planform**: (1) The contour of the stream, as viewed from above. (2) The pattern formed by a waterway as viewed from above. The primary types of planform are meandering, braided, and straight.

**Pool**: (1) A reach of stream that is characterized by deep, low-velocity water and a smooth surface; frequently used by fish for resting and cover. (2) A portion of the stream with reduced current velocity (during base flow), with water deeper than the adjacent areas. (3) A relatively deep section of a stream or river marked by slower velocities and finer bed materials. 

**Profile**: A depiction of certain characteristics, usually depth, bed configuration, substrate, and velocity, of the cross section of a stream. 

### Q

### R

**Raster**: 

**Reach**: (1) A selected portion of a channel's length between any defined limits. (2) A relatively long, straight section of river (river pilot term).

**Relative Elevation Model (REM)**: 

**Riffle**: (1) A region of the stream characterized by partially or completely submerged coarser bed materials and shallower faster-moving water. Riffle areas tend to support higher densities of benthic invertebrates (important for fish). (2) A reach of stream that is characterized by shallow, fast-moving water broken by the presence of rocks and boulders. (3) A shallow, rapid section of stream where the water surface is broken into waves by obstructions that are wholly or partly submerged. (4) A shallow section of a stream where the stream flows at relatively greater velocities over coarse bed material or bedrock, resulting in a rapids of comparatively little fall. 

**Riparian**: (1) Pertaining to or situated on the bank of a natural body of flowing water. (2) Located on the banks of a stream or other body of water. (3) Relating to or living on or near the bank of a watercourse. These zones range in width from narrow bands in desert or mountainous areas to wide bands which occur in low gradient valleys and more humid regions. (4) Pertaining to anything connected with, adjacent to, or influenced by a stream, river, lake, reservoir, or other water body.

### S

**Scour**: (1) The erosive act of flowing (running) water in streams that removes (excavates) and carries away material from the bed and banks; wearing away by abrasive action. Scour may occur in both earth and solid rock material and can be classed as general, contraction, or local scour. (2) Erosion due to flowing water; usually considered as being localized as opposed to general bed degradation. See also bridge scour.  

**Sediment Load**: (1) The amount of sediment transported by a particular watercourse; a function of the flow velocity patterns produced by the hydraulic characteristics of the water body and particle size.  The sediment load includes both suspended sediment in the water column and bedload sediment transported by rolling, sliding, or skipping along the water bottom. (2) The mass or volume of sediment being moved by a stream past a given point in a given unit of time. The total of bed load plus suspended load. For practical purposes, interchangeable with sediment discharge.

**Slope**: (1) The ratio of the change in elevation over distance. (2) Degree of deviation from horizontal; expressed either as a percentage, as a numerical ratio, in degrees, or as rise or fall per unit distance of stream length. As a percentage, the number of meters (feet) of rise or fall in 100 m (100 ft) of horizontal distance. As a ratio, it is the number of feet of horizontal(H) to the number of feet vertical(V). E.g., a 25 percent slope is equal to a 4H:1V slope, is equal to a slope of approximately 14 degrees, and is equal to 0.25 ft per ft. Slope is sometimes described by the phrase "the rise over the run". (3) Gradient of a stream. (4) Inclination of the face of an embankment, expressed as the ratio of horizontal to vertical projection; or (5) The face of an inclined embankment or cut slope.In hydraulics it is expressed as percent or in decimal form. 

**Soil**: (1) The layer of material at the land surface that supports plant growth. (2) Unconsolidated mineral and organic surface material that has been sufficiently modified and acted upon by physical, chemical, and biological agents so that it will support plant growth.  

**Stage**: (1) Height of the water surface above an established datum plane, such as in a river above a predetermined point that may (or may not) be at the channel floor. (2) Elevation of water surface above any chosen reference plane. Also known as water level or gage height. (3) Water surface elevation of a stream, lake, reservoir, or other water body referenced to a datum plane, which may be MSL, NGVD, or an arbitrary datum plane, such as the average low water elevation at a given location, or an even more arbitrary value, such as a surveyor's estimate of the elevation of the river bed at some point in time. A given value for stage is meaningless for scientific or engineering purposes without a definition of the datum plane to which it is referenced (usually referred to as "zero" of the gage). 

**Stream**: (1) A general term for a body of water flowing by gravity; natural watercourse containing water at least part of the year.  In hydrology, the term is generally applied to the water flowing in a natural narrow channel as distinct from a canal.  (2) A natural watercourse containing flowing water at least part of the year, supporting a community of plants and animals within the stream channel and the riparian vegetation zone. (3) Any body of running water that moves under gravity to progressively lower levels, in a                      relatively narrow but clearly defined channel on the ground surface, in a subterranean cavern, or beneath or in a glacier. It is a mixture of water and dissolved, suspended, or entrained matter. (4) streams range in size from small creeks to large river. 

-   **Perennial:** One that flows continuously throughout the year. 

-   **Ephemeral:** One that flows briefly only in direct response to precipitation in the immediate locality and whose channel is at all times above the water table. 

-   **Intermittent or Seasonal:** (1) One in contact with the groundwater table that flows only at certain times of the year as when the water table is high and/or when it receives water from springs or from some surface source, such as melting snow in mountainous areas.  It ceases to flow above the streambed when losses from evaporation or seepage exceed the available stream flow. (2) One that flows only at certain times of the year, usually on a seasonal basis. 

**Streamflow**: The movement of water and sediment through a channel. 

**Study Area**: Observable area that encompasses the problems associated with a particular study and/or site.

**Substrate**: (1) The mineral and organic material that is from the bed of stream; (2) The surface beneath a wetland, lake, or stream in which organisms grow or to which organisms are attached. (3) The composition of a streambed, including either mineral or organic materials. (4) Material that forms an attachment medium for organisms. (5) The foundation upon which all things exist. E.g., soil is a substrate that supports plants, animals, buildings, roads, and other structures. The bed material that the stream rests on is also a substrate. This includes the layers of material underlying the bed surface layer. 

### T

**Thalweg:**The line connecting the lowest or deepest points along a stream bed in the longitudinal direction. The deepest point in a cross section or the trace formed by the deepest portion of the channel changes from side to side within the channel. The momentum of the flow affects the cross-sectional geometry of the stream. Thalweg surveys are taken along the channel at the lowest point in the cross section. Comparison of several thalweg surveys taken at different points in time allows the engineer or geomorphologist to chart the change in the bed elevation through time.

**Terrain Visualization**:

**Topography**: (1) The general configuration of a land surface or any part of the Earth’s surface, including its relief and the position of its natural and man-made features. (2) Shape and physical features of land. 

**Tributaries**: Any channel, waterway, or outlet that conveys water into a stream. 

**Turbulence**: Motion of fluids in which local velocities and pressures fluctuate irregularly in a random manner.  Opposite of laminar flow.  In general terms, the irregular motion of a flowing fluid.  Open channel flow is almost always turbulent to some degree. 

### U

### V

### W

**Water Surface**: 

**Waterway**:

**Wetted Perimeter**:

### X

### Y

### Z
